name: 'dbt_bq_getting_started'
version: '1.0.0'
config-version: 2

profile: 'dbt_bq_getting_started'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

require-dbt-version: [">=1.5.0", "<2.0.0"]

vars:
  # Default variables for BigQuery project and dataset names
  project_id: "{{ env_var('DBT_PROJECT_ID', 'your-project-id') }}"
  raw_schema: "{{ env_var('DBT_RAW_SCHEMA', 'raw') }}"
  core_schema: "{{ env_var('DBT_CORE_SCHEMA', 'core') }}"
  mart_schema: "{{ env_var('DBT_MART_SCHEMA', 'mart') }}"

models:
  dbt_bq_getting_started:
    # STAGING LAYER: Source-aligned data with minimal transformations
    staging:
      +materialized: view
      +schema: "{{ var('raw_schema') }}"
      +tags: ["staging"]
      
      # Source-specific configurations for event tables
      stripe:
        +schema: "{{ var('raw_schema') }}_stripe"
        events:
          +materialized: incremental
          +incremental_strategy: merge
          +unique_key: "event_id"
      shopify:
        +schema: "{{ var('raw_schema') }}_shopify"
        events:
          +materialized: incremental
          +incremental_strategy: merge
          +unique_key: "event_id"
      
    # CORE LAYER: Core business entities and metrics
    core:
      +materialized: incremental
      +schema: "{{ var('core_schema') }}"
      +tags: ["core"]
      +incremental_strategy: merge
      
      # Entity-specific configurations
      customers:
        +schema: "{{ var('core_schema') }}_customers"
      products:
        +schema: "{{ var('core_schema') }}_products"
      orders:
        +schema: "{{ var('core_schema') }}_orders"
      
    # MARTS LAYER: Business-specific data marts
    marts:
      +materialized: table
      +schema: "{{ var('mart_schema') }}"
      +tags: ["marts"]
      
      # Business domain configurations
      finance:
        +schema: "{{ var('mart_schema') }}_finance"
      marketing:
        +schema: "{{ var('mart_schema') }}_marketing"
      sales:
        +schema: "{{ var('mart_schema') }}_sales"

seeds:
  dbt_bq_getting_started:
    +schema: seeds

# On-run-end hooks for logging and monitoring
on-run-end:
  - "{{ logging.log_model_timing() }}"

# Add required packages
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1
  - package: calogica/dbt_expectations
    version: 0.10.1
